# Generated by Django 3.1.6 on 2021-04-01 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('submission_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('text_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField(max_length=1000)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrec.document')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('protected_name', models.CharField(max_length=25)),
                ('text_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrec.text')),
            ],
        ),
    ]
